"""init

Revision ID: 933672c12290
Revises: 
Create Date: 2023-02-22 23:23:40.529186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933672c12290'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
