"""add readers

Revision ID: bd3b105e007f
Revises: 933672c12290
Create Date: 2023-02-22 23:33:07.960630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3b105e007f'
down_revision = '933672c12290'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reade')
    op.add_column('books', sa.Column('reder_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_books_reder_id'), 'books', ['reder_id'], unique=False)
    op.create_foreign_key(None, 'books', 'readers', ['reder_id'], ['id'])
    op.add_column('readers', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('readers', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('readers', 'author')
    op.drop_column('readers', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readers', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('readers', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('readers', 'last_name')
    op.drop_column('readers', 'first_name')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_reder_id'), table_name='books')
    op.drop_column('books', 'reder_id')
    op.create_table('reade',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reade_pkey')
    )
    # ### end Alembic commands ###
