"""modifie reader name

Revision ID: c9080aa67289
Revises: bd3b105e007f
Create Date: 2023-02-23 00:35:26.078581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9080aa67289'
down_revision = 'bd3b105e007f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reader_id', sa.Integer(), nullable=False))
    op.drop_index('ix_books_reder_id', table_name='books')
    op.create_index(op.f('ix_books_reader_id'), 'books', ['reader_id'], unique=False)
    op.drop_constraint('books_reder_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'readers', ['reader_id'], ['id'])
    op.drop_column('books', 'reder_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reder_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_reder_id_fkey', 'books', 'readers', ['reder_id'], ['id'])
    op.drop_index(op.f('ix_books_reader_id'), table_name='books')
    op.create_index('ix_books_reder_id', 'books', ['reder_id'], unique=False)
    op.drop_column('books', 'reader_id')
    # ### end Alembic commands ###
