"""correcting field name on complaints model (Complainer_id to complainer_id)

Revision ID: ef316151561c
Revises: 492e76bedf8e
Create Date: 2023-03-20 16:48:01.092124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef316151561c'
down_revision = '492e76bedf8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('complainer_id', sa.Integer(), nullable=False))
    op.drop_constraint('complaints_Complainer_id_fkey', 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'users', ['complainer_id'], ['id'])
    op.drop_column('complaints', 'Complainer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('Complainer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key('complaints_Complainer_id_fkey', 'complaints', 'users', ['Complainer_id'], ['id'])
    op.drop_column('complaints', 'complainer_id')
    # ### end Alembic commands ###
